#!/usr/bin/env python

###############################################################################
###############################################################################

from distutils.core import setup

###############################################################################
###############################################################################

setup(
    name='fx-bitstamp',
    version='0.0.1',
    packages=[
        'lib.python3.3.site-packages.distribute-0.6.34-py3.3.egg._markerlib',
        'lib.python3.3.site-packages.distribute-0.6.34-py3.3.egg.setuptools',
        'lib.python3.3.site-packages.distribute-0.6.34-py3.3.egg.setuptools.tests',
        'lib.python3.3.site-packages.distribute-0.6.34-py3.3.egg.setuptools.command',
        'lib.python3.3.site-packages.pip-1.3.1-py3.3.egg.pip',
        'lib.python3.3.site-packages.pip-1.3.1-py3.3.egg.pip.commands',
        'lib.python3.3.site-packages.pip-1.3.1-py3.3.egg.pip.vcs',
        'lib.python3.3.site-packages.pip-1.3.1-py3.3.egg.pip.backwardcompat',
        'lib.python3.3.site-packages.IPython',
        'lib.python3.3.site-packages.IPython.kernel',
        'lib.python3.3.site-packages.IPython.lib',
        'lib.python3.3.site-packages.IPython.lib.tests',
        'lib.python3.3.site-packages.IPython.core',
        'lib.python3.3.site-packages.IPython.core.magics',
        'lib.python3.3.site-packages.IPython.core.tests',
        'lib.python3.3.site-packages.IPython.external',
        'lib.python3.3.site-packages.IPython.external.simplegeneric',
        'lib.python3.3.site-packages.IPython.external.pexpect',
        'lib.python3.3.site-packages.IPython.external.decorators',
        'lib.python3.3.site-packages.IPython.external.argparse',
        'lib.python3.3.site-packages.IPython.external.decorator',
        'lib.python3.3.site-packages.IPython.external.ssh',
        'lib.python3.3.site-packages.IPython.external.path',
        'lib.python3.3.site-packages.IPython.parallel',
        'lib.python3.3.site-packages.IPython.parallel.engine',
        'lib.python3.3.site-packages.IPython.parallel.apps',
        'lib.python3.3.site-packages.IPython.parallel.tests',
        'lib.python3.3.site-packages.IPython.parallel.controller',
        'lib.python3.3.site-packages.IPython.parallel.client',
        'lib.python3.3.site-packages.IPython.parallel.scripts',
        'lib.python3.3.site-packages.IPython.zmq',
        'lib.python3.3.site-packages.IPython.zmq.pylab',
        'lib.python3.3.site-packages.IPython.zmq.gui',
        'lib.python3.3.site-packages.IPython.zmq.tests',
        'lib.python3.3.site-packages.IPython.extensions',
        'lib.python3.3.site-packages.IPython.extensions.tests',
        'lib.python3.3.site-packages.IPython.nbformat',
        'lib.python3.3.site-packages.IPython.nbformat.v2',
        'lib.python3.3.site-packages.IPython.nbformat.v2.tests',
        'lib.python3.3.site-packages.IPython.nbformat.v3',
        'lib.python3.3.site-packages.IPython.nbformat.v3.tests',
        'lib.python3.3.site-packages.IPython.nbformat.tests',
        'lib.python3.3.site-packages.IPython.nbformat.v1',
        'lib.python3.3.site-packages.IPython.nbformat.v1.tests',
        'lib.python3.3.site-packages.IPython.frontend',
        'lib.python3.3.site-packages.IPython.frontend.terminal',
        'lib.python3.3.site-packages.IPython.frontend.terminal.console',
        'lib.python3.3.site-packages.IPython.frontend.terminal.console.tests',
        'lib.python3.3.site-packages.IPython.frontend.terminal.tests',
        'lib.python3.3.site-packages.IPython.frontend.qt',
        'lib.python3.3.site-packages.IPython.frontend.qt.console',
        'lib.python3.3.site-packages.IPython.frontend.qt.console.tests',
        'lib.python3.3.site-packages.IPython.frontend.html',
        'lib.python3.3.site-packages.IPython.frontend.html.notebook',
        'lib.python3.3.site-packages.IPython.frontend.html.notebook.tests',
        'lib.python3.3.site-packages.IPython.utils',
        'lib.python3.3.site-packages.IPython.utils.tests',
        'lib.python3.3.site-packages.IPython.testing',
        'lib.python3.3.site-packages.IPython.testing.plugin',
        'lib.python3.3.site-packages.IPython.testing.tests',
        'lib.python3.3.site-packages.IPython.config',
        'lib.python3.3.site-packages.IPython.config.tests',
        'lib.python3.3.site-packages.IPython.config.profile',
        'lib.python3.3.site-packages.IPython.scripts',
        'lib.python3.3.site-packages.requests',
        'lib.python3.3.site-packages.requests.packages',
        'lib.python3.3.site-packages.requests.packages.charade',
        'lib.python3.3.site-packages.requests.packages.urllib3',
        'lib.python3.3.site-packages.requests.packages.urllib3.packages',
        'lib.python3.3.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
        'lib.python3.3.site-packages.zmq',
        'lib.python3.3.site-packages.zmq.sugar',
        'lib.python3.3.site-packages.zmq.green',
        'lib.python3.3.site-packages.zmq.green.eventloop',
        'lib.python3.3.site-packages.zmq.core',
        'lib.python3.3.site-packages.zmq.devices',
        'lib.python3.3.site-packages.zmq.cffi_core',
        'lib.python3.3.site-packages.zmq.tests',
        'lib.python3.3.site-packages.zmq.utils',
        'lib.python3.3.site-packages.zmq.ssh',
        'lib.python3.3.site-packages.zmq.eventloop',
        'lib.python3.3.site-packages.zmq.eventloop.minitornado',
        'lib.python3.3.site-packages.zmq.eventloop.minitornado.platform',
        'lib.python3.3.site-packages.zmq.log', 'lib.python3.3.collections',
        'lib.python3.3.encodings', 'lib.python3.3.distutils',
        'lib.python3.3.importlib'],

    url='https://bitbucket.org/hsk81/fx-bitstamp',
    license='GPLv3',
    author='Hasan Karahan',
    author_email='hasan.karahan81@gmail.com',
    description='Algorithmic trading on Bitstamp.net'
)

###############################################################################
###############################################################################
